apiVersion: v1
kind: PersistentVolume
metadata:
  name: huggingface-cache-pv-rmw
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /data/huggingface-cache