{{- range .Values.models }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .name }}
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - port: 8000
    targetPort: {{ .name }}
    name: {{ .name }}
  selector:
    app: {{ .name }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-service-monitor-{{ .name }}
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: {{ .name }}
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    scheme: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app: {{ .name }}
  namespaceSelector:
    matchNames:
    - {{ $.Values.namespace }}
---
{{- end }}