apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-router
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.router.replicaCount }}
  selector:
    matchLabels:
      app: vllm-router
  template:
    metadata:
      labels:
        app: vllm-router
    spec:
      serviceAccountName: vllm-router-sa
      containers:
      - name: vllm-router
        image: {{ .Values.router.image }}
        imagePullPolicy: Always
        command: ["bash", "-c"]
        args: ["cd /app; python3 router.py"]
        ports:
        - containerPort: 8000
          name: vllm-port
        volumeMounts:
        - name: config-volume
          mountPath: /etc/vllm-router
      volumes:
      - name: config-volume
        configMap:
          name: vllm-router-config